"""Add base tables

Revision ID: 0c883b4d5ad5
Revises: ceffe1f6e266
Create Date: 2026-09-19 12:56:22.317362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c883b4d5ad5'
down_revision: Union[str, Sequence[str], None] = 'ceffe1f6e266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_jurisdictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('regulator', sa.String(), nullable=True),
    sa.Column('patent_duration_years', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reference_jurisdictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_jurisdictions_id'), ['id'], unique=False)

    op.create_table('reference_plants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('botanical_name', sa.String(), nullable=False),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('tkdl_status', sa.Boolean(), nullable=True),
    sa.Column('abs_risk', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reference_plants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_plants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reference_plants_name'), ['name'], unique=False)

    op.create_table('reference_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('authority', sa.String(), nullable=True),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('last_verified', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reference_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_sources_id'), ['id'], unique=False)

    op.create_table('translation_cache',
    sa.Column('source_hash', sa.String(), nullable=False),
    sa.Column('target_language', sa.String(), nullable=False),
    sa.Column('source_text', sa.String(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('source_hash', 'target_language')
    )
    with op.batch_alter_table('translation_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_cache_source_hash'), ['source_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_cache_target_language'), ['target_language'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('report_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_id'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('translation_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_cache_target_language'))
        batch_op.drop_index(batch_op.f('ix_translation_cache_source_hash'))

    op.drop_table('translation_cache')
    with op.batch_alter_table('reference_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_sources_id'))

    op.drop_table('reference_sources')
    with op.batch_alter_table('reference_plants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_plants_name'))
        batch_op.drop_index(batch_op.f('ix_reference_plants_id'))

    op.drop_table('reference_plants')
    with op.batch_alter_table('reference_jurisdictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_jurisdictions_id'))

    op.drop_table('reference_jurisdictions')
    # ### end Alembic commands ###
