"""Drop unused static tables

Revision ID: 947fc4992101
Revises: 0c883b4d5ad5
Create Date: 2026-09-19 13:00:27.259402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '947fc4992101'
down_revision: Union[str, Sequence[str], None] = '0c883b4d5ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reference_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_sources_id'))

    op.drop_table('reference_sources')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('reference_plants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_plants_id'))
        batch_op.drop_index(batch_op.f('ix_reference_plants_name'))

    op.drop_table('reference_plants')
    with op.batch_alter_table('reference_jurisdictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_jurisdictions_id'))

    op.drop_table('reference_jurisdictions')
    with op.batch_alter_table('translation_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_cache_source_hash'))
        batch_op.drop_index(batch_op.f('ix_translation_cache_target_language'))

    op.drop_table('translation_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_cache',
    sa.Column('source_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('translation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('source_hash', 'target_language', name=op.f('translation_cache_pkey'))
    )
    with op.batch_alter_table('translation_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_cache_target_language'), ['target_language'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_cache_source_hash'), ['source_hash'], unique=False)

    op.create_table('reference_jurisdictions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('regulator', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('patent_duration_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('reference_jurisdictions_pkey'))
    )
    with op.batch_alter_table('reference_jurisdictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_jurisdictions_id'), ['id'], unique=False)

    op.create_table('reference_plants',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('botanical_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('family', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tkdl_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('abs_risk', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('reference_plants_pkey'))
    )
    with op.batch_alter_table('reference_plants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_plants_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_reference_plants_id'), ['id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('query', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('jurisdiction', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('report_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_sessions_pkey'))
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_id'), ['id'], unique=False)

    op.create_table('reference_sources',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('authority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('jurisdiction', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_verified', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('reference_sources_pkey'))
    )
    with op.batch_alter_table('reference_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_sources_id'), ['id'], unique=False)

    # ### end Alembic commands ###
